version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: wl-api-img
    # ports:
    #   - 3333:3333
    container_name: wl-api
    restart: always
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: wl-client-img
    # ports:
    #   - 3000:3000
    container_name: wl-client
    restart: always
networks:
  default:
    external: true
    name: nginx